/**
 * Admin Wizard generator orchestration module
 * Creates the admin wizard backend + frontend layers for fullstack projects
 */

import { promises as fs } from 'node:fs';
import path from 'node:path';
import {
  generateAdminAuthMiddleware,
  generateMiddlewareInit,
  generateAdminDbRoutes,
} from './templates/admin-wizard-python.js';
import {
  generateUseAdminApiHook,
  generateDbStatusBanner,
  generateConnectionForm,
  generateMigrationProgress,
  generateDbSetupStepper,
  generateAdminIndex,
} from './templates/admin-wizard-react.js';

/** Python dependencies required by the admin wizard */
export const ADMIN_WIZARD_PYTHON_DEPS = ['python-multipart>=0.0.7'];

/**
 * Create a directory if it doesn't exist
 */
async function ensureDir(dirPath: string): Promise<void> {
  await fs.mkdir(dirPath, { recursive: true });
}

/**
 * Write a file with content
 */
async function writeFile(filePath: string, content: string): Promise<void> {
  await fs.writeFile(filePath, content, 'utf-8');
}

/**
 * Generate the complete admin wizard layer (backend middleware/routes + frontend components)
 *
 * Creates middleware/, routes/admin_db.py in the backend, and admin/ components
 * in the frontend. Also augments requirements.txt with admin dependencies.
 *
 * @param projectDir - Root project directory (contains apps/)
 * @param packageName - Python package name (snake_case)
 * @returns List of absolute file paths created
 */
export async function generateAdminWizardLayer(
  projectDir: string,
  packageName: string
): Promise<string[]> {
  const backendDir = path.join(projectDir, 'apps', 'backend');
  const srcPkgDir = path.join(backendDir, 'src', packageName);
  const frontendDir = path.join(projectDir, 'apps', 'frontend');
  const filesCreated: string[] = [];

  // Ensure directories
  await ensureDir(path.join(srcPkgDir, 'middleware'));
  await ensureDir(path.join(frontendDir, 'src', 'admin'));

  // Define all files to generate
  const files: Array<{ path: string; content: string }> = [
    // Backend: middleware
    {
      path: path.join(srcPkgDir, 'middleware', '__init__.py'),
      content: generateMiddlewareInit(),
    },
    {
      path: path.join(srcPkgDir, 'middleware', 'admin_auth.py'),
      content: generateAdminAuthMiddleware(),
    },
    // Backend: admin routes
    {
      path: path.join(srcPkgDir, 'routes', 'admin_db.py'),
      content: generateAdminDbRoutes(packageName),
    },
    // Frontend: admin components
    {
      path: path.join(frontendDir, 'src', 'admin', 'useAdminApi.ts'),
      content: generateUseAdminApiHook(),
    },
    {
      path: path.join(frontendDir, 'src', 'admin', 'DbStatusBanner.tsx'),
      content: generateDbStatusBanner(),
    },
    {
      path: path.join(frontendDir, 'src', 'admin', 'ConnectionForm.tsx'),
      content: generateConnectionForm(),
    },
    {
      path: path.join(frontendDir, 'src', 'admin', 'MigrationProgress.tsx'),
      content: generateMigrationProgress(),
    },
    {
      path: path.join(frontendDir, 'src', 'admin', 'DbSetupStepper.tsx'),
      content: generateDbSetupStepper(),
    },
    {
      path: path.join(frontendDir, 'src', 'admin', 'index.ts'),
      content: generateAdminIndex(),
    },
  ];

  // Write all files
  for (const file of files) {
    await writeFile(file.path, file.content);
    filesCreated.push(file.path);
  }

  // Augment requirements.txt with admin deps
  const reqPath = path.join(backendDir, 'requirements.txt');
  try {
    const existingReqs = await fs.readFile(reqPath, 'utf-8');
    if (!existingReqs.includes('# Admin')) {
      const adminSection = `\n# Admin\n${ADMIN_WIZARD_PYTHON_DEPS.join('\n')}\n`;
      await writeFile(reqPath, existingReqs.trimEnd() + adminSection);
    }
  } catch {
    // requirements.txt doesn't exist yet - will be created by the main generator
  }

  return filesCreated;
}

/**
 * Get the list of relative file paths generated by the admin wizard layer
 *
 * @param packageName - Python package name (snake_case)
 * @returns List of relative file paths
 */
export function getAdminWizardFiles(packageName: string): string[] {
  return [
    // Backend
    `apps/backend/src/${packageName}/middleware/__init__.py`,
    `apps/backend/src/${packageName}/middleware/admin_auth.py`,
    `apps/backend/src/${packageName}/routes/admin_db.py`,
    // Frontend
    'apps/frontend/src/admin/useAdminApi.ts',
    'apps/frontend/src/admin/DbStatusBanner.tsx',
    'apps/frontend/src/admin/ConnectionForm.tsx',
    'apps/frontend/src/admin/MigrationProgress.tsx',
    'apps/frontend/src/admin/DbSetupStepper.tsx',
    'apps/frontend/src/admin/index.ts',
  ];
}
