/**
 * Website strategy type definitions
 * Defines the strategic marketing document, site architecture,
 * design tokens, and brand assets contract for website generation
 */

import { z } from 'zod';

/**
 * Navigation item for site header/footer
 */
export interface NavItem {
  label: string;
  href: string;
  children?: NavItem[];
}

/**
 * Footer section with links
 */
export interface FooterSection {
  title: string;
  links: Array<{ label: string; href: string }>;
}

/**
 * Page definition in site architecture
 */
export interface SiteArchitecturePage {
  path: string;
  title: string;
  purpose: string;
  pageType:
    | 'landing'
    | 'pricing'
    | 'solution'
    | 'use-cases'
    | 'about'
    | 'contact'
    | 'blog'
    | 'docs'
    | 'legal';
  sections: string[];
  seoKeywords: string[];
  conversionGoal: string;
}

/**
 * Complete website strategy document
 * Generated by AI from product context, user docs, and market inputs
 */
export interface WebsiteStrategyDocument {
  icp: {
    primaryPersona: string;
    painPoints: string[];
    goals: string[];
    objections: string[];
  };
  positioning: {
    category: string;
    differentiators: string[];
    valueProposition: string;
    proofPoints: string[];
  };
  messaging: {
    headline: string;
    subheadline: string;
    elevatorPitch: string;
    longDescription: string;
  };
  seoStrategy: {
    primaryKeywords: string[];
    secondaryKeywords: string[];
    longTailKeywords: string[];
    titleTemplates: Record<string, string>;
    metaDescriptions: Record<string, string>;
  };
  siteArchitecture: {
    pages: SiteArchitecturePage[];
    navigation: NavItem[];
    footerSections: FooterSection[];
  };
  conversionStrategy: {
    primaryCta: { text: string; href: string };
    secondaryCta: { text: string; href: string };
    trustSignals: string[];
    socialProof: string[];
    leadCapture: 'none' | 'webhook' | 'resend' | 'postmark';
  };
  competitiveContext: {
    category: string;
    competitors: string[];
    differentiators: string[];
  };
}

/**
 * Strategy metadata for caching and staleness detection
 */
export interface StrategyMetadata {
  /** SHA-256 of (docs + spec + tokens) for staleness detection */
  inputHash: string;
  /** ISO timestamp of generation */
  generatedAt: string;
  /** Schema version */
  version: number;
}

/**
 * Design tokens extracted from project config or brand docs
 */
export interface DesignTokens {
  colors: Record<string, string>;
  fonts: { heading: string; body: string; mono?: string };
  borderRadius: string;
  source: 'tailwind-config' | 'css-variables' | 'brand-docs' | 'defaults';
}

/**
 * Brand assets contract for deterministic logo/favicon placement
 */
export interface BrandAssetsContract {
  /** Discovered source path for logo */
  logoPath?: string;
  /** Canonical output path: public/brand/logo.{ext} */
  logoOutputPath: string;
  /** Discovered source path for favicon */
  faviconPath?: string;
  /** Primary brand color */
  primaryColor?: string;
  /** Full color scheme */
  colorScheme?: Record<string, string>;
}

// --- Zod Schemas ---

export const NavItemSchema: z.ZodType<NavItem> = z.lazy(() =>
  z.object({
    label: z.string().min(1),
    href: z.string().min(1),
    children: z.array(NavItemSchema).optional(),
  })
);

export const FooterSectionSchema = z.object({
  title: z.string().min(1),
  links: z.array(
    z.object({
      label: z.string().min(1),
      href: z.string().min(1),
    })
  ),
});

export const SiteArchitecturePageSchema = z.object({
  path: z.string().min(1),
  title: z.string().min(1),
  purpose: z.string(),
  pageType: z.enum([
    'landing',
    'pricing',
    'solution',
    'use-cases',
    'about',
    'contact',
    'blog',
    'docs',
    'legal',
  ]),
  sections: z.array(z.string()),
  seoKeywords: z.array(z.string()),
  conversionGoal: z.string(),
});

export const WebsiteStrategySchema = z.object({
  icp: z.object({
    primaryPersona: z.string().min(1),
    painPoints: z.array(z.string()),
    goals: z.array(z.string()),
    objections: z.array(z.string()),
  }),
  positioning: z.object({
    category: z.string().min(1),
    differentiators: z.array(z.string()),
    valueProposition: z.string().min(1),
    proofPoints: z.array(z.string()),
  }),
  messaging: z.object({
    headline: z.string().min(1),
    subheadline: z.string().min(1),
    elevatorPitch: z.string().min(1),
    longDescription: z.string().min(1),
  }),
  seoStrategy: z.object({
    primaryKeywords: z.array(z.string()),
    secondaryKeywords: z.array(z.string()),
    longTailKeywords: z.array(z.string()),
    titleTemplates: z.record(z.string(), z.string()),
    metaDescriptions: z.record(z.string(), z.string()),
  }),
  siteArchitecture: z.object({
    pages: z.array(SiteArchitecturePageSchema),
    navigation: z.array(NavItemSchema),
    footerSections: z.array(FooterSectionSchema),
  }),
  conversionStrategy: z.object({
    primaryCta: z.object({ text: z.string().min(1), href: z.string().min(1) }),
    secondaryCta: z.object({ text: z.string().min(1), href: z.string().min(1) }),
    trustSignals: z.array(z.string()),
    socialProof: z.array(z.string()),
    leadCapture: z.enum(['none', 'webhook', 'resend', 'postmark']),
  }),
  competitiveContext: z.object({
    category: z.string(),
    competitors: z.array(z.string()),
    differentiators: z.array(z.string()),
  }),
});

export const StrategyMetadataSchema = z.object({
  inputHash: z.string().min(1),
  generatedAt: z.string().min(1),
  version: z.number(),
});

export const DesignTokensSchema = z.object({
  colors: z.record(z.string(), z.string()),
  fonts: z.object({
    heading: z.string(),
    body: z.string(),
    mono: z.string().optional(),
  }),
  borderRadius: z.string(),
  source: z.enum(['tailwind-config', 'css-variables', 'brand-docs', 'defaults']),
});

export const BrandAssetsContractSchema = z.object({
  logoPath: z.string().optional(),
  logoOutputPath: z.string().min(1),
  faviconPath: z.string().optional(),
  primaryColor: z.string().optional(),
  colorScheme: z.record(z.string(), z.string()).optional(),
});
