/**
 * Python project templates
 * Provides template files for Python project generation
 */

/**
 * Generate pyproject.toml content
 */
export function generatePyprojectToml(projectName: string): string {
  return `[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "${projectName}"
version = "0.1.0"
description = "Generated by Popeye CLI"
readme = "README.md"
requires-python = ">=3.11"
license = {text = "MIT"}
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = []

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "pytest-asyncio>=0.21.0",
    "black>=23.0.0",
    "ruff>=0.1.0",
    "mypy>=1.0.0",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
asyncio_mode = "auto"
addopts = "-v --cov=src --cov-report=term-missing"

[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
select = ["E", "F", "I", "N", "W", "UP"]
ignore = ["E501"]

[tool.mypy]
python_version = "3.11"
strict = true
warn_return_any = true
warn_unused_ignores = true
`;
}

/**
 * Generate requirements.txt content
 */
export function generateRequirementsTxt(): string {
  return `# Core dependencies
# Add your dependencies here

# Development dependencies
pytest>=7.0.0
pytest-cov>=4.0.0
pytest-asyncio>=0.21.0
black>=23.0.0
ruff>=0.1.0
mypy>=1.0.0
`;
}

/**
 * Generate main __init__.py content
 */
export function generateMainInit(projectName: string): string {
  return `"""
${projectName}

Generated by Popeye CLI
"""

__version__ = "0.1.0"
`;
}

/**
 * Generate main.py content
 */
export function generateMainPy(projectName: string): string {
  return `"""
Main entry point for ${projectName}.

This module serves as the primary entry point for the application.
"""

import logging

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
)
logger = logging.getLogger(__name__)


def main() -> None:
    """
    Main function.

    Entry point for the application.
    """
    logger.info("Starting ${projectName}")
    # TODO: Implement main functionality
    print("Hello from ${projectName}!")


if __name__ == "__main__":
    main()
`;
}

/**
 * Generate conftest.py content
 */
export function generateConftest(): string {
  return `"""
Pytest configuration and fixtures.

This module contains shared fixtures used across all tests.
"""

import pytest


@pytest.fixture
def sample_data() -> dict:
    """
    Provide sample data for tests.

    Returns:
        dict: Sample data dictionary.
    """
    return {"key": "value", "number": 42}
`;
}

/**
 * Generate test_main.py content
 */
export function generateTestMain(projectName: string): string {
  return `"""
Tests for main module.
"""

import pytest

# Import the module to test
# from src.${projectName.replace(/-/g, '_')}.main import main


class TestMain:
    """Test cases for main module."""

    def test_placeholder(self) -> None:
        """
        Placeholder test.

        This test should be replaced with actual tests.
        """
        assert True

    def test_sample_with_fixture(self, sample_data: dict) -> None:
        """
        Test using sample_data fixture.

        Args:
            sample_data: Fixture providing sample data.
        """
        assert sample_data["key"] == "value"
        assert sample_data["number"] == 42
`;
}

/**
 * Generate Dockerfile content
 */
export function generateDockerfile(projectName: string): string {
  return `# Python base image
FROM python:3.11-slim as base

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1 \\
    PYTHONUNBUFFERED=1 \\
    PIP_NO_CACHE_DIR=1 \\
    PIP_DISABLE_PIP_VERSION_CHECK=1

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY src/ ./src/

# Production stage
FROM base as production

# Create non-root user
RUN adduser --disabled-password --gecos '' appuser
USER appuser

# Run the application
CMD ["python", "-m", "src.${projectName.replace(/-/g, '_')}.main"]

# Development stage
FROM base as development

# Install dev dependencies
RUN pip install --no-cache-dir pytest pytest-cov black ruff mypy

# Copy tests
COPY tests/ ./tests/

CMD ["pytest", "tests/", "-v"]
`;
}

/**
 * Generate docker-compose.yml content
 */
export function generateDockerCompose(projectName: string): string {
  return `version: "3.8"

services:
  app:
    build:
      context: .
      target: production
    container_name: ${projectName}
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data

  dev:
    build:
      context: .
      target: development
    container_name: ${projectName}-dev
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    command: ["python", "-m", "src.${projectName.replace(/-/g, '_')}.main"]
`;
}

/**
 * Generate .gitignore content
 */
export function generateGitignore(): string {
  return `# Byte-compiled / optimized / DLL files
__pycache__/
*.py[cod]
*$py.class

# C extensions
*.so

# Distribution / packaging
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg

# PyInstaller
*.manifest
*.spec

# Installer logs
pip-log.txt
pip-delete-this-directory.txt

# Unit test / coverage reports
htmlcov/
.tox/
.nox/
.coverage
.coverage.*
.cache
nosetests.xml
coverage.xml
*.cover
*.py,cover
.hypothesis/
.pytest_cache/

# Translations
*.mo
*.pot

# Environments
.env
.venv
env/
venv/
ENV/

# IDE
.idea/
.vscode/
*.swp
*.swo

# mypy
.mypy_cache/

# ruff
.ruff_cache/

# Project specific
.popeye/
data/
*.log
`;
}

/**
 * Generate .env.example content
 */
export function generateEnvExample(): string {
  return `# Environment variables
# Copy this file to .env and fill in the values

# Application settings
APP_ENV=development
DEBUG=true
LOG_LEVEL=INFO

# Add your environment variables below
`;
}

/**
 * Generate README.md content
 */
export function generateReadme(projectName: string, description: string): string {
  return `# ${projectName}

${description || 'Generated by Popeye CLI'}

## Installation

\`\`\`bash
# Create virtual environment
python -m venv venv
source venv/bin/activate  # On Windows: venv\\Scripts\\activate

# Install dependencies
pip install -e ".[dev]"
\`\`\`

## Usage

\`\`\`bash
python -m src.${projectName.replace(/-/g, '_')}.main
\`\`\`

## Development

### Running Tests

\`\`\`bash
pytest tests/ -v
\`\`\`

### Code Formatting

\`\`\`bash
black src/ tests/
ruff check src/ tests/ --fix
\`\`\`

### Type Checking

\`\`\`bash
mypy src/
\`\`\`

## Docker

\`\`\`bash
# Build and run with Docker Compose
docker-compose up --build

# Run in development mode
docker-compose run dev
\`\`\`

## License

MIT
`;
}

/**
 * Generate Makefile content
 */
export function generateMakefile(_projectName: string): string {
  return `.PHONY: install dev test lint format typecheck clean docker-build docker-run

install:
\tpip install -e .

dev:
\tpip install -e ".[dev]"

test:
\tpytest tests/ -v --cov=src --cov-report=term-missing

lint:
\truff check src/ tests/

format:
\tblack src/ tests/
\truff check src/ tests/ --fix

typecheck:
\tmypy src/

clean:
\trm -rf build/ dist/ *.egg-info/ .pytest_cache/ .mypy_cache/ .ruff_cache/ __pycache__/
\tfind . -type d -name "__pycache__" -exec rm -rf {} +

docker-build:
\tdocker-compose build

docker-run:
\tdocker-compose up
`;
}
