/**
 * TypeScript project templates
 * Provides template files for TypeScript project generation
 */

/**
 * Generate package.json content
 */
export function generatePackageJson(projectName: string, description?: string): string {
  return JSON.stringify(
    {
      name: projectName,
      version: '1.0.0',
      description: description || 'Generated by Popeye CLI',
      main: './dist/index.js',
      type: 'module',
      scripts: {
        build: 'tsc',
        dev: 'tsc --watch',
        start: 'node dist/index.js',
        test: 'vitest run',
        'test:watch': 'vitest',
        'test:coverage': 'vitest run --coverage',
        lint: 'eslint src --ext .ts',
        'lint:fix': 'eslint src --ext .ts --fix',
        format: 'prettier --write "src/**/*.ts"',
        typecheck: 'tsc --noEmit',
        clean: 'rm -rf dist',
      },
      keywords: [],
      author: '',
      license: 'MIT',
      engines: {
        node: '>=18.0.0',
      },
      dependencies: {},
      devDependencies: {
        '@types/node': '^20.17.6',
        '@typescript-eslint/eslint-plugin': '^8.14.0',
        '@typescript-eslint/parser': '^8.14.0',
        '@vitest/coverage-v8': '^2.1.4',
        eslint: '^9.14.0',
        prettier: '^3.3.3',
        typescript: '^5.6.3',
        vitest: '^2.1.4',
      },
    },
    null,
    2
  );
}

/**
 * Generate tsconfig.json content
 */
export function generateTsconfig(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2022',
        module: 'NodeNext',
        moduleResolution: 'NodeNext',
        lib: ['ES2022'],
        outDir: './dist',
        rootDir: './src',
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        forceConsistentCasingInFileNames: true,
        declaration: true,
        declarationMap: true,
        sourceMap: true,
        resolveJsonModule: true,
        noImplicitAny: true,
        noUnusedLocals: true,
        noUnusedParameters: true,
        noImplicitReturns: true,
        noFallthroughCasesInSwitch: true,
      },
      include: ['src/**/*'],
      exclude: ['node_modules', 'dist', 'tests'],
    },
    null,
    2
  );
}

/**
 * Generate vitest.config.ts content
 */
export function generateVitestConfig(): string {
  return `import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    globals: true,
    environment: 'node',
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
      exclude: ['node_modules/', 'dist/', 'tests/'],
    },
  },
});
`;
}

/**
 * Generate eslint.config.js content
 */
export function generateEslintConfig(): string {
  return `import eslint from '@eslint/js';
import tseslint from '@typescript-eslint/eslint-plugin';
import tsparser from '@typescript-eslint/parser';

export default [
  eslint.configs.recommended,
  {
    files: ['src/**/*.ts'],
    languageOptions: {
      parser: tsparser,
      parserOptions: {
        ecmaVersion: 2022,
        sourceType: 'module',
      },
      globals: {
        console: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
      },
    },
    plugins: {
      '@typescript-eslint': tseslint,
    },
    rules: {
      ...tseslint.configs.recommended.rules,
      '@typescript-eslint/explicit-function-return-type': 'warn',
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      '@typescript-eslint/no-explicit-any': 'warn',
    },
  },
];
`;
}

/**
 * Generate .prettierrc content
 */
export function generatePrettierrc(): string {
  return JSON.stringify(
    {
      semi: true,
      singleQuote: true,
      tabWidth: 2,
      trailingComma: 'es5',
      printWidth: 100,
    },
    null,
    2
  );
}

/**
 * Generate main index.ts content
 */
export function generateIndexTs(projectName: string): string {
  return `/**
 * ${projectName}
 *
 * Generated by Popeye CLI
 */

/**
 * Main function
 */
export function main(): void {
  console.log('Hello from ${projectName}!');
}

// Run if executed directly
main();
`;
}

/**
 * Generate test file content
 */
export function generateTestFile(projectName: string): string {
  return `import { describe, it, expect } from 'vitest';
import { main } from '../src/index.js';

describe('${projectName}', () => {
  describe('main', () => {
    it('should run without errors', () => {
      expect(() => main()).not.toThrow();
    });
  });

  describe('placeholder tests', () => {
    it('should pass basic assertion', () => {
      expect(true).toBe(true);
    });

    it('should handle sample data', () => {
      const data = { key: 'value', number: 42 };
      expect(data.key).toBe('value');
      expect(data.number).toBe(42);
    });
  });
});
`;
}

/**
 * Generate Dockerfile content
 */
export function generateDockerfile(_projectName: string): string {
  return `# Node.js base image
FROM node:20-slim as base

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm ci --only=production

# Copy built files
COPY dist/ ./dist/

# Production stage
FROM base as production

# Create non-root user
RUN adduser --disabled-password --gecos '' appuser
USER appuser

CMD ["node", "dist/index.js"]

# Development stage
FROM node:20-slim as development

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

CMD ["npm", "run", "dev"]
`;
}

/**
 * Generate docker-compose.yml content
 */
export function generateDockerCompose(projectName: string): string {
  return `version: "3.8"

services:
  app:
    build:
      context: .
      target: production
    container_name: ${projectName}
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data

  dev:
    build:
      context: .
      target: development
    container_name: ${projectName}-dev
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    command: ["npm", "run", "dev"]
`;
}

/**
 * Generate .gitignore content
 */
export function generateGitignore(): string {
  return `# Dependencies
node_modules/

# Build output
dist/
build/

# IDE
.idea/
.vscode/
*.swp
*.swo

# Environment
.env
.env.local
.env.*.local

# Logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Testing
coverage/
.nyc_output/

# OS files
.DS_Store
Thumbs.db

# Project specific
.popeye/
data/
`;
}

/**
 * Generate .env.example content
 */
export function generateEnvExample(): string {
  return `# Environment variables
# Copy this file to .env and fill in the values

# Application settings
NODE_ENV=development
DEBUG=true
LOG_LEVEL=info

# Add your environment variables below
`;
}

/**
 * Generate README.md content
 */
export function generateReadme(projectName: string, description?: string): string {
  return `# ${projectName}

${description || 'Generated by Popeye CLI'}

## Installation

\`\`\`bash
npm install
\`\`\`

## Usage

\`\`\`bash
# Build
npm run build

# Run
npm start

# Development mode
npm run dev
\`\`\`

## Development

### Running Tests

\`\`\`bash
npm test

# With coverage
npm run test:coverage

# Watch mode
npm run test:watch
\`\`\`

### Code Quality

\`\`\`bash
# Lint
npm run lint

# Format
npm run format

# Type check
npm run typecheck
\`\`\`

## Docker

\`\`\`bash
# Build and run with Docker Compose
docker-compose up --build

# Run in development mode
docker-compose run dev
\`\`\`

## License

MIT
`;
}
